name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 15 6 * * 0
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy on'
        type: environment
        required: true
        
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "with ref ${{ github.ref }}"
  
      - uses: actions/checkout@3.3.0

      - name: List files
        run: |
          echo "content of ${{ github.repository }}"
          tree
          
